### ISSUE TITLE
readme error

### ISSUE THREAD

**Issue by cryptopig** [Gaurav-Ban22/gaurav-ban22#1]
In Line 15 of your README.txt file, "I am a _proud_ Ubuntu user" should be changed to "Unfortunately, and due to my current circumstances, I am forced to use an Ubuntu-based system. My Linux computer can barely run for 10 minutes without requiring several external fans in the form of a lap desk. I sincerely apologize for my lack of skill because I am the average Linux user."

**Comment by Gaurav-Ban22** [comment]
cope harder windows user

**Comment by cryptopig** [comment]
linux
